# Minimal cryptogen template for 3 orgs (Manufacturer, Distributor, Retailer)
OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Manufacturer
    Domain: manufacturer.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Distributor
    Domain: distributor.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Retailer
    Domain: retailer.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
